'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d',{alpha:false});
const W=960,H=540,VIEW=470,FOV=Math.PI/3;
const $=s=>document.querySelector(s);
const map=[
'1111111111111111',
'1000000000000001',
'1000020020000001',
'1000020020000001',
'1000000000010001',
'1110111011010101',
'1000000000000101',
'1002200022000001',
'1002200022000001',
'1000000000000001',
'1011101101110101',
'1000000000000001',
'1002000200020001',
'1000000000000001',
'1000000000000031',
'1111111111111111'].map(r=>r.split('').map(Number));
const weapons=[{name:'Смена №7 · IPA',ammo:Infinity,cool:.5,damage:42,speed:10,type:'bottle'},{name:'Котёл 13 · стаут',ammo:18,cool:.8,damage:95,speed:7,type:'can'},{name:'Пробкомёт',ammo:120,cool:.12,damage:19,speed:24,type:'cork'},{name:'Пенная пушка',ammo:80,cool:.09,damage:11,speed:8,type:'foam'}];
let player,enemies,items,shots=[],particles=[],running=false,started=false,won=false,dead=false,kills=0,weapon=0,fire=false,showMap=false,clock=0,cooldown=0,kick=0,hurt=0,toastTime=0,audioEnabled=true,step=0;
const keys=new Set(),depth=new Float32Array(W);
function reset(){GameAudio.reset();player={x:3.5,y:2.5,a:Math.PI/2,hp:100};enemies=[[3.5,4.4,0],[6.5,2.5,1],[10.5,3.5,2],[12.5,6.5,0],[4.5,6.5,1],[6.5,8.5,2],[11.5,9.5,0],[2.5,9.5,2],[4.5,12.5,1],[8.5,11.5,0],[12.5,12.5,2],[12.5,14.5,1]].map(([x,y,type],i)=>({x,y,type,hp:[75,110,55][type],max:[75,110,55][type],attack:0,hit:0,seed:i*3.1}));items=[[1.5,4.5,'health'],[6.5,6.5,'ammo'],[13.5,3.5,'ammo'],[1.5,11.5,'health'],[9.5,13.5,'ammo'],[13.5,13.5,'health']].map(([x,y,type])=>({x,y,type}));shots=[];particles=[];kills=0;weapon=0;weapons.forEach((w,i)=>w.ammo=[Infinity,18,120,80][i]);cooldown=0;kick=0;hurt=0;dead=false;won=false;clock=0;updateHUD();}
function solid(x,y){return map[Math.floor(y)]?.[Math.floor(x)]!==0;}
function move(o,dx,dy,r=.22){if(!solid(o.x+dx+Math.sign(dx)*r,o.y-r)&&!solid(o.x+dx+Math.sign(dx)*r,o.y+r))o.x+=dx;if(!solid(o.x-r,o.y+dy+Math.sign(dy)*r)&&!solid(o.x+r,o.y+dy+Math.sign(dy)*r))o.y+=dy;}
function sight(x,y,tx,ty){let d=Math.hypot(tx-x,ty-y),n=Math.ceil(d/.15);for(let i=1;i<n;i++)if(solid(x+(tx-x)*i/n,y+(ty-y)*i/n))return false;return true;}
function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;toastTime=2.6;}
function updateHUD(){$('#health').textContent=Math.ceil(player.hp);$('#healthbar').style.width=player.hp+'%';$('#weaponname').textContent=weapons[weapon].name;$('#ammo').textContent=weapons[weapon].ammo===Infinity?'∞':weapons[weapon].ammo;$('#kills').innerHTML=kills+' <em>/ 12</em>';document.querySelectorAll('.weapon').forEach((b,i)=>b.classList.toggle('active',i===weapon));}
function choose(i){weapon=i;kick=.18;updateHUD();if(running)toast(weapons[i].name);}
function start(){const fresh=!started||dead||won;if(fresh)reset();started=true;running=true;$('#overlay').hidden=true;$('#hud').hidden=false;$('#crosshair').style.display='block';$('#status').textContent='Очисти цех и доберись до выхода';canvas.requestPointerLock?.()?.catch(()=>{});toast('Не дай микробам испортить партию!');GameAudio.resume().then(()=>{if(running&&fresh)GameAudio.say('start',true);});}
function pause(){if(!running)return;GameAudio.pause();running=false;fire=false;keys.clear();$('#overlay').hidden=false;$('.intro h1').innerHTML='ПЕРЕРЫВ<br><span>НА ПЕНУ</span>';$('.intro p').innerHTML='Смена ещё не закончена.<br>Цех ждёт своего пивовара.';$('#start').innerHTML='Продолжить смену <span>↗</span>';document.exitPointerLock?.();}
function finish(win){GameAudio.pause();GameAudio.say(win?'win':'death',true);running=false;won=win;dead=!win;fire=false;keys.clear();document.exitPointerLock?.();$('#overlay').hidden=false;$('.intro h1').innerHTML=win?'ПАРТИЯ<br><span>СПАСЕНА</span>':'СМЕНА<br><span>ПРОПАЛА</span>';$('.intro p').innerHTML=win?'Все 12 микробов уничтожены.<br>Пивоварня снова варит. За тебя!':`Микробы оказались настойчивее.<br>Уничтожено: ${kills} из 12. Попробуй ещё раз.`;$('#start').innerHTML='Новая смена <span>↗</span>';}
function shoot(){let w=weapons[weapon];if(cooldown>0)return;if(w.ammo<=0){toast('Припасы закончились. Найди ящик или возьми бутылку: 1');cooldown=.4;return;}w.ammo--;cooldown=w.cool;kick=1;let count=weapon===3?3:1;for(let i=0;i<count;i++){let a=player.a+(i-(count-1)/2)*.1;shots.push({x:player.x+Math.cos(a)*.25,y:player.y+Math.sin(a)*.25,dx:Math.cos(a)*w.speed,dy:Math.sin(a)*w.speed,type:w.type,damage:w.damage,life:weapon===3?.65:2.5,age:0});}GameAudio.shot(w.type);GameAudio.say('shoot');updateHUD();}
function burst(x,y,color,n=14){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=Math.random()*1.8;particles.push({x,y,dx:Math.cos(a)*s,dy:Math.sin(a)*s,z:Math.random()*.6,color,life:.35+Math.random()*.3});}}
function damage(e,d){if(e.hp<=0)return;e.hp-=d;e.hit=.16;if(e.hp<=0){kills++;burst(e.x,e.y,['#b6c955','#d5a94d','#c2b3d6'][e.type],25);GameAudio.kill();GameAudio.say('kill');if(kills===12)toast('Цех очищен! Выход — в дальнем правом углу. Смотри карту: M');updateHUD();}}
function impact(s){const dx=s.x-player.x,dy=s.y-player.y;GameAudio.impact(s.type,Math.hypot(dx,dy),(-dx*Math.sin(player.a)+dy*Math.cos(player.a))/5);burst(s.x,s.y,s.type==='foam'?'#fff1c0':s.type==='can'?'#e5bc64':'#a0bb70',s.type==='can'?35:10);if(s.type==='can'){enemies.forEach(e=>{let d=Math.hypot(e.x-s.x,e.y-s.y);if(d<2.1&&sight(s.x,s.y,e.x,e.y))damage(e,s.damage*(1-d/2.5));});}}
function tick(dt){clock+=dt;cooldown=Math.max(0,cooldown-dt);kick=Math.max(0,kick-dt*4);hurt=Math.max(0,hurt-dt*2);toastTime-=dt;if(toastTime<=0)$('#toast').style.opacity=0;if(!running)return;
if(keys.has('ArrowLeft'))player.a-=dt*2;if(keys.has('ArrowRight'))player.a+=dt*2;
let f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),s=Number(keys.has('KeyD'))-Number(keys.has('KeyA'));let len=Math.hypot(f,s)||1,speed=(keys.has('ShiftLeft')?3.8:2.6)*dt;move(player,(Math.cos(player.a)*f-Math.sin(player.a)*s)/len*speed,(Math.sin(player.a)*f+Math.cos(player.a)*s)/len*speed);if(f||s)step+=dt*9;GameAudio.update(dt,Boolean(f||s),keys.has('ShiftLeft'));
if(fire||keys.has('Space'))shoot();
for(let e of enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);e.attack-=dt;let d=Math.hypot(e.x-player.x,e.y-player.y);if(d<8&&sight(e.x,e.y,player.x,player.y)){if(d>.72){let v=[.78,.56,1.05][e.type]*dt;move(e,(player.x-e.x)/d*v,(player.y-e.y)/d*v,.23);}else if(e.attack<=0){player.hp=Math.max(0,player.hp-[9,15,7][e.type]);hurt=1;e.attack=.85;GameAudio.hit();GameAudio.say(player.hp<30?'low':'hurt');updateHUD();if(player.hp<=0){finish(false);return;}}}}
for(let sh of shots){sh.life-=dt;sh.age+=dt;let n=Math.ceil(Math.hypot(sh.dx,sh.dy)*dt/.1);for(let j=0;j<n&&sh.life>0;j++){sh.x+=sh.dx*dt/n;sh.y+=sh.dy*dt/n;if(solid(sh.x,sh.y)){sh.x-=sh.dx*dt/n;sh.y-=sh.dy*dt/n;impact(sh);sh.life=0;break;}let target=enemies.find(e=>e.hp>0&&Math.hypot(e.x-sh.x,e.y-sh.y)<.34);if(target){if(sh.type!=='can')damage(target,sh.damage);impact(sh);sh.life=0;}}if(sh.life<=0&&sh.type==='can'&&sh.age>=2.5)impact(sh);}
shots=shots.filter(s=>s.life>0);particles.forEach(p=>{p.life-=dt;p.x+=p.dx*dt;p.y+=p.dy*dt;p.z-=dt*.4;});particles=particles.filter(p=>p.life>0);
items=items.filter(i=>{if(Math.hypot(i.x-player.x,i.y-player.y)<.65){if(i.type==='health'){if(player.hp>=100)return true;player.hp=Math.min(100,player.hp+35);toast('Перерыв на воду: +35 здоровья');}else{weapons[1].ammo+=8;weapons[2].ammo+=45;weapons[3].ammo+=35;toast('Ящик припасов: банки, пробки и пена');}GameAudio.say('pickup');updateHUD();return false;}return true;});
if(kills===12&&Math.hypot(player.x-13.8,player.y-14.5)<.85)finish(true);
}
function makeTexture(kind){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.fillStyle=kind===2?'#a66436':kind===3?'#335a3c':'#797663';g.fillRect(0,0,128,128);if(kind===1){for(let y=0;y<128;y+=24){g.fillStyle='#3f493d';g.fillRect(0,y,128,3);for(let x=(y/24%2)*32;x<128;x+=64)g.fillRect(x,y,3,24);g.fillStyle='#b5a789';g.fillRect(0,y+3,128,1);}g.fillStyle='#384a3b';g.fillRect(0,88,128,40);g.fillStyle='#d7bb70';g.fillRect(0,87,128,3);}else if(kind===2){let grad=g.createLinearGradient(0,0,128,0);grad.addColorStop(0,'#4d3828');grad.addColorStop(.35,'#c89155');grad.addColorStop(.55,'#dfaa65');grad.addColorStop(1,'#613d28');g.fillStyle=grad;g.fillRect(0,0,128,128);for(let y of [12,98]){g.fillStyle='#423f30';g.fillRect(0,y,128,7);g.fillStyle='#c1b987';g.fillRect(0,y,128,2);for(let x=8;x<128;x+=23){g.fillStyle='#e1c488';g.fillRect(x,y+2,3,3);}}g.fillStyle='#314331';g.fillRect(30,38,68,39);g.strokeStyle='#ddc386';g.strokeRect(33,41,62,33);g.fillStyle='#e9d6a1';g.font='bold 16px monospace';g.textAlign='center';g.font='bold 9px monospace';g.fillText('ХМЕЛЬНОЙ',64,53);g.fillText('ДОЗОР',64,63);g.font='8px monospace';g.fillText('TANK 04',64,71);g.fillStyle='#413e2e';g.fillRect(60,109,12,19);}else{g.fillStyle='#1d3427';g.fillRect(8,5,112,123);g.strokeStyle='#d8c88a';g.strokeRect(12,10,104,114);g.fillStyle='#c8d994';g.font='bold 20px monospace';g.fillText('EXIT',38,52);g.font='30px monospace';g.fillText('→',49,90);}let seed=31;for(let i=0;i<1800;i++){seed=(seed*16807)%2147483647;let x=seed%128;seed=(seed*16807)%2147483647;let y=seed%128;g.fillStyle=i%2?'#ffffff0c':'#00000012';g.fillRect(x,y,1,1);}return c;}
const textures=[null,makeTexture(1),makeTexture(2),makeTexture(3)];
// A supplied studio logo on selected brick walls, with the ordinary wall as load fallback.
const studioWall=makeTexture(1),studioLogo=document.createElement('img');
studioLogo.onload=()=>{const g=studioWall.getContext('2d');const size=82;const scale=Math.min(size/studioLogo.naturalWidth,size/studioLogo.naturalHeight);const w=studioLogo.naturalWidth*scale,h=studioLogo.naturalHeight*scale;g.drawImage(studioLogo,64-w/2,64-h/2,w,h);};
studioLogo.src='assets/art/brand/logo.png';
function wallTexture(tile,x,y){return tile===1&&((x===4&&y===5)||(x===10&&y===10)||(x===0&&y===3))?studioWall:textures[tile];}

function sprite(type){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.lineWidth=4;g.strokeStyle='#25362d';const ellipse=(x,y,rx,ry,col)=>{g.fillStyle=col;g.beginPath();g.ellipse(x,y,rx,ry,0,0,7);g.fill();g.stroke();};if(type.startsWith('enemy')){let t=Number(type.slice(-1)),col=['#9cac44','#c5a453','#9d8bb5'][t];g.fillStyle='#0005';g.beginPath();g.ellipse(64,116,40,8,0,0,7);g.fill();for(let i=0;i<12;i++){let a=i*Math.PI/6,x=64+Math.cos(a)*43,y=61+Math.sin(a)*40;g.strokeStyle='#25362d';g.lineWidth=7;g.beginPath();g.moveTo(64+Math.cos(a)*30,61+Math.sin(a)*30);g.lineTo(x,y);g.stroke();ellipse(x,y,5,5,col);}ellipse(64,64,36,t===1?43:33,col);ellipse(40,106,13,9,col);ellipse(87,106,13,9,col);g.strokeStyle='#25362d';ellipse(49,52,13,15,'#f3df9c');ellipse(80,52,13,15,'#f3df9c');ellipse(53,55,4,7,'#202820');ellipse(76,55,4,7,'#202820');g.fillStyle='#26382a';g.beginPath();g.moveTo(42,76);g.quadraticCurveTo(64,95,88,75);g.lineTo(82,96);g.lineTo(51,98);g.closePath();g.fill();g.fillStyle='#f0deb2';for(let x=49;x<85;x+=10){g.beginPath();g.moveTo(x,80);g.lineTo(x+7,81);g.lineTo(x+3,90);g.fill();}g.fillStyle='#ffffff33';g.fillRect(37,66,6,4);g.fillRect(82,69,8,5);g.fillStyle='#31473066';g.fillRect(58,30,6,5);g.fillRect(33,81,5,8);g.fillRect(90,65,5,9);if(t===1){g.fillStyle='#e9d799';g.fillRect(46,17,38,9);g.fillRect(53,8,24,12);}if(t===2){g.strokeStyle='#b9a3c8';g.lineWidth=6;for(let x of [20,107]){g.beginPath();g.moveTo(x,50);g.lineTo(x-10,23);g.lineTo(x+3,30);g.stroke();}}}else if(type==='health'){g.fillStyle='#0005';g.fillRect(20,104,90,10);g.fillStyle='#d9dab5';g.fillRect(28,40,72,67);g.strokeRect(28,40,72,67);g.fillStyle='#526e42';g.fillRect(54,48,20,48);g.fillRect(40,62,48,19);g.strokeRect(50,29,28,12);}else if(type==='ammo'){g.fillStyle='#976d3d';g.fillRect(15,54,100,57);g.strokeRect(15,54,100,57);for(let x=26;x<110;x+=22){g.fillStyle='#345336';g.fillRect(x,26,13,41);g.fillStyle='#d2b669';g.fillRect(x+3,16,7,14);}g.fillStyle='#ddc98e';g.fillRect(31,72,68,25);g.fillStyle='#3d462b';g.font='bold 12px monospace';g.font='bold 9px monospace';g.fillText('ХМЕЛЬНОЙ',37,83);g.fillText('ДОЗОР',46,93);}else if(type==='bottle'){g.fillStyle='#ddc88b';g.fillRect(54,7,20,9);g.fillStyle='#426d39';g.fillRect(55,16,18,30);g.fillRect(43,45,42,69);g.strokeRect(43,45,42,69);g.fillStyle='#e8d39a';g.fillRect(43,68,42,29);g.fillStyle='#344b2c';g.font='bold 17px monospace';g.fillText('№7',51,88);g.fillStyle='#acc773';g.fillRect(48,49,5,17);}else if(type==='can'){g.fillStyle='#c5b69b';g.fillRect(39,30,50,78);g.strokeRect(39,30,50,78);g.fillStyle='#44342c';g.fillRect(40,44,48,52);g.fillStyle='#efc86d';g.font='bold 12px monospace';g.fillText('КОТЁЛ',44,68);g.fillText('13',57,86);g.fillStyle='#f1dcac';g.fillRect(42,32,44,5);}else{ellipse(64,64,18,18,type==='foam'?'#f4e4b8':'#bba479');}return c;}
const sprites=Object.fromEntries(['enemy0','enemy1','enemy2','health','ammo','bottle','can','cork','foam'].map(s=>[s,sprite(s)]));
function background(){ctx.fillStyle='#263629';ctx.fillRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,VIEW/2);sky.addColorStop(0,'#17271f');sky.addColorStop(1,'#58604b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,VIEW/2);let floor=ctx.createLinearGradient(0,VIEW/2,0,VIEW);floor.addColorStop(0,'#756849');floor.addColorStop(1,'#302f24');ctx.fillStyle=floor;ctx.fillRect(0,VIEW/2,W,H);for(let y=VIEW/2+5;y<VIEW;y+=3){let d=VIEW/(2*(y-VIEW/2));let alpha=Math.min(.17,.8/d);ctx.fillStyle=`rgba(195,171,109,${alpha})`;if(Math.floor(d+player.y)%2===0)ctx.fillRect(0,y,W,1);} }
function drawWorld(){background();for(let x=0;x<W;x+=2){let camera=(2*x/W-1)*Math.tan(FOV/2),rx=Math.cos(player.a)-Math.sin(player.a)*camera,ry=Math.sin(player.a)+Math.cos(player.a)*camera;let mx=Math.floor(player.x),my=Math.floor(player.y),ddx=Math.abs(1/rx),ddy=Math.abs(1/ry),sx=rx<0?-1:1,sy=ry<0?-1:1,distx=(rx<0?player.x-mx:mx+1-player.x)*ddx,disty=(ry<0?player.y-my:my+1-player.y)*ddy,side=0,tile=0;for(let j=0;j<64;j++){if(distx<disty){distx+=ddx;mx+=sx;side=0;}else{disty+=ddy;my+=sy;side=1;}tile=map[my]?.[mx]??1;if(tile)break;}let d=Math.max(.05,side?disty-ddy:distx-ddx);depth[x]=depth[x+1]=d;let wall=side?player.x+d*rx:player.y+d*ry;wall-=Math.floor(wall);let column=Math.min(127,Math.floor(wall*128));if((side===0&&rx<0)||(side===1&&ry>0))column=127-column;let h=VIEW/d,y=(VIEW-h)/2;ctx.drawImage(wallTexture(tile,mx,my),column,0,1,128,x,y,2,h);ctx.fillStyle=`rgba(9,20,14,${Math.min(.83,d*.058+(side?.16:0))})`;ctx.fillRect(x,y,2,h);}}
function project(x,y){let dx=x-player.x,dy=y-player.y,d=dx*Math.cos(player.a)+dy*Math.sin(player.a);return{d,x:W/2+(-dx*Math.sin(player.a)+dy*Math.cos(player.a))*W/(2*Math.tan(FOV/2)*d)};}
function bill(img,x,y,size=1,z=0,hit=0){let p=project(x,y);if(p.d<.15)return;let h=VIEW/p.d*size,w=h,left=p.x-w/2,top=VIEW/2+VIEW/p.d*.5-h-z*VIEW/p.d;if(left>W||left+w<0)return;ctx.globalAlpha=1;for(let sx=Math.max(0,Math.floor(left));sx<Math.min(W,left+w);sx+=2){if(p.d>=depth[sx])continue;ctx.drawImage(img,Math.max(0,Math.floor((sx-left)/w*128)),0,1,128,sx,top,2,h);}if(hit>0&&p.x>=0&&p.x<W&&p.d<depth[Math.floor(p.x)]){ctx.fillStyle='#f8df9a';ctx.fillRect(p.x-16,top-9,32*hit/.16,3);} }
function drawSprites(){let all=[...enemies.filter(e=>e.hp>0).map(e=>({...e,img:sprites['enemy'+e.type],size:.85,z:Math.sin(clock*5+e.seed)*.025})),...items.map(i=>({...i,img:sprites[i.type],size:.52})),...shots.map(s=>({...s,img:sprites[s.type],size:s.type==='foam'?.2:.24,z:.35+Math.sin(Math.min(1,s.age)*Math.PI)*.2}))];all.sort((a,b)=>Math.hypot(b.x-player.x,b.y-player.y)-Math.hypot(a.x-player.x,a.y-player.y));for(let e of all)bill(e.img,e.x,e.y,e.size,e.z||0,e.hit||0);for(let q of particles){let p=project(q.x,q.y);if(p.d<.1||p.x<0||p.x>=W||p.d>depth[Math.floor(p.x)])continue;let y=VIEW/2+(.4-q.z)*VIEW/p.d,r=Math.min(20,5/p.d);ctx.fillStyle=q.color;ctx.fillRect(p.x,y,r,r);}}
function gun(){
 const throwing=weapon<2,bob=running?Math.sin(step)*5:0;
 const recoil=throwing?Math.sin(kick*Math.PI)*42:kick*22;
 ctx.save();ctx.imageSmoothingEnabled=true;
 ctx.translate(W*.63+bob,VIEW+18+recoil);
 ctx.rotate(throwing?-.04-kick*.32:-.03-kick*.07);
 const art=WeaponArt.get(weapon);ctx.drawImage(art,-240,-365,480,400);
 if(!throwing&&kick>.55){ctx.globalAlpha=(kick-.55)/.45;ctx.fillStyle=weapon===2?'#ffdfa0':'#fff1d2';
  for(let i=0;i<7;i++){const a=i*Math.PI*2/7;ctx.beginPath();ctx.ellipse(-24+Math.cos(a)*15,-310+Math.sin(a)*11,weapon===2?7:14,weapon===2?4:11,a,0,Math.PI*2);ctx.fill();}}
 ctx.restore();
}
function minimap(){let scale=showMap?15:6,ox=W-16-map[0].length*scale,oy=16;ctx.fillStyle='#10241fe8';ctx.fillRect(ox-7,oy-7,16*scale+14,16*scale+14);map.forEach((row,y)=>row.forEach((t,x)=>{ctx.fillStyle=t===2?'#ac8652':t===3?'#d9d883':t?'#63725b':'#233c2f';ctx.fillRect(ox+x*scale,oy+y*scale,scale-1,scale-1);}));if(showMap){for(let e of enemies){if(e.hp<=0)continue;ctx.fillStyle='#d28966';ctx.fillRect(ox+e.x*scale-2,oy+e.y*scale-2,4,4);}for(let i of items){ctx.fillStyle='#c5dca0';ctx.fillRect(ox+i.x*scale-2,oy+i.y*scale-2,4,4);}}ctx.fillStyle='#ffd778';ctx.beginPath();ctx.arc(ox+player.x*scale,oy+player.y*scale,3,0,7);ctx.fill();ctx.strokeStyle='#ffd778';ctx.beginPath();ctx.moveTo(ox+player.x*scale,oy+player.y*scale);ctx.lineTo(ox+(player.x+Math.cos(player.a)*.7)*scale,oy+(player.y+Math.sin(player.a)*.7)*scale);ctx.stroke();}
function render(){ctx.imageSmoothingEnabled=false;drawWorld();drawSprites();if(started){gun();minimap();}else{ctx.fillStyle='#112c1933';ctx.fillRect(0,0,W,H);}if(hurt>0){ctx.fillStyle=`rgba(172,56,27,${hurt*.3})`;ctx.fillRect(0,0,W,H);}}
document.querySelectorAll('[data-volume]').forEach(input=>{const channel=input.dataset.volume;input.value=Math.round(GameAudio.volumes[channel]*100);$('#value-'+channel).textContent=input.value+'%';input.addEventListener('input',()=>{GameAudio.setVolume(channel,Number(input.value)/100);$('#value-'+channel).textContent=input.value+'%';});});
$('#audio-settings').addEventListener('toggle',()=>{if($('#audio-settings').open&&running)pause();});
$('#start').addEventListener('click',start);$('#sound').addEventListener('click',()=>{audioEnabled=!audioEnabled;GameAudio.setEnabled(audioEnabled);$('#sound').setAttribute('aria-label',audioEnabled?'Выключить звук':'Включить звук');$('#sound').textContent='Звук: '+(audioEnabled?'вкл.':'выкл.');});document.querySelectorAll('.weapon').forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.weapon)));
window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){pause();return;}if(e.code==='KeyM'&&!e.repeat)showMap=!showMap;if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))choose(Number(e.code.slice(-1))-1);if(running){keys.add(e.code);if(e.code==='Space'&&!e.repeat)shoot();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();GameAudio.pause();}});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&running&&matchMedia('(pointer:fine)').matches)pause();});document.addEventListener('mousemove',e=>{if(running&&document.pointerLockElement===canvas)player.a+=e.movementX*.0025;});canvas.addEventListener('mousedown',e=>{if(e.button!==0||!running)return;fire=true;shoot();if(document.pointerLockElement!==canvas)canvas.requestPointerLock?.()?.catch(()=>{});});window.addEventListener('mouseup',()=>fire=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(running){e.preventDefault();choose((weapon+(e.deltaY>0?1:3))%4);}},{passive:false});
for(let b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(let name of ['pointerup','pointercancel'])b.addEventListener(name,()=>keys.delete(b.dataset.key));}$('#touchfire').addEventListener('pointerdown',e=>{e.preventDefault();e.target.setPointerCapture(e.pointerId);fire=true;});for(let name of ['pointerup','pointercancel'])$('#touchfire').addEventListener(name,()=>fire=false);$('#touchswap').addEventListener('click',()=>choose((weapon+1)%4));let touchX=null;canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchX=e.clientX;});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&touchX!==null&&running){player.a+=(e.clientX-touchX)*.009;touchX=e.clientX;}});canvas.addEventListener('pointerup',()=>touchX=null);
document.querySelectorAll('.weapon-thumb').forEach((c,i)=>{c.getContext('2d').drawImage(WeaponArt.get(i),110,80,530,550,0,0,c.width,c.height);});
reset();let previous=performance.now();function frame(now){let dt=Math.min(.04,(now-previous)/1000);previous=now;tick(dt);render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
