'use strict';
// World renderer: walls, floor, sprites and particles drawn from a per-frame view object built by game.js.
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d',{alpha:false});
const W=960,H=540,VIEW=470,FOV=Math.PI/3;
const Renderer=(()=>{
 const depth=new Float32Array(W),stats={},current={index:0,level:null,map:null};let V=null;
 function makeTexture(kind){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.fillStyle=kind===2?'#a66436':kind===3?'#335a3c':'#797663';g.fillRect(0,0,128,128);if(kind===1){for(let y=0;y<128;y+=24){g.fillStyle='#3f493d';g.fillRect(0,y,128,3);for(let x=(y/24%2)*32;x<128;x+=64)g.fillRect(x,y,3,24);g.fillStyle='#b5a789';g.fillRect(0,y+3,128,1);}g.fillStyle='#384a3b';g.fillRect(0,88,128,40);g.fillStyle='#d7bb70';g.fillRect(0,87,128,3);}else if(kind===2){let grad=g.createLinearGradient(0,0,128,0);grad.addColorStop(0,'#4d3828');grad.addColorStop(.35,'#c89155');grad.addColorStop(.55,'#dfaa65');grad.addColorStop(1,'#613d28');g.fillStyle=grad;g.fillRect(0,0,128,128);for(let y of [12,98]){g.fillStyle='#423f30';g.fillRect(0,y,128,7);g.fillStyle='#c1b987';g.fillRect(0,y,128,2);for(let x=8;x<128;x+=23){g.fillStyle='#e1c488';g.fillRect(x,y+2,3,3);}}g.fillStyle='#314331';g.fillRect(30,38,68,39);g.strokeStyle='#ddc386';g.strokeRect(33,41,62,33);g.fillStyle='#e9d6a1';g.font='bold 16px monospace';g.textAlign='center';g.font='bold 9px monospace';g.fillText('ХМЕЛЬНОЙ',64,53);g.fillText('ДОЗОР',64,63);g.font='8px monospace';g.fillText('TANK 04',64,71);g.fillStyle='#413e2e';g.fillRect(60,109,12,19);}else{g.fillStyle='#1d3427';g.fillRect(8,5,112,123);g.strokeStyle='#d8c88a';g.strokeRect(12,10,104,114);g.fillStyle='#c8d994';g.font='bold 20px monospace';g.fillText('EXIT',38,52);g.font='30px monospace';g.fillText('→',49,90);}let seed=31;for(let i=0;i<1800;i++){seed=(seed*16807)%2147483647;let x=seed%128;seed=(seed*16807)%2147483647;let y=seed%128;g.fillStyle=i%2?'#ffffff0c':'#00000012';g.fillRect(x,y,1,1);}return c;}
 const textures=[null,makeTexture(1),makeTexture(2),makeTexture(3)];
 // A supplied studio logo on selected brick walls, with the ordinary wall as load fallback.
 const studioWarehouseWall=document.createElement('canvas');studioWarehouseWall.width=studioWarehouseWall.height=128;studioWarehouseWall.getContext('2d').drawImage(SceneArt.warehouseWall,0,0);
 const studioMaltWall=document.createElement('canvas');studioMaltWall.width=studioMaltWall.height=128;studioMaltWall.getContext('2d').drawImage(SceneArt.maltWall,0,0);
 const studioWall=makeTexture(1),studioPackWall=document.createElement('canvas'),studioLogo=document.createElement('img');
 studioPackWall.width=studioPackWall.height=128;
 studioPackWall.getContext('2d').drawImage(SceneArt.packWall,0,0);
 // Compensate for the raycaster’s horizontal/vertical projection ratio so logos appear circular.
 studioLogo.onload=()=>{const size=82;const scale=Math.min(size/studioLogo.naturalWidth,size/studioLogo.naturalHeight);const w=studioLogo.naturalWidth*scale*(2*VIEW*Math.tan(FOV/2)/W),h=studioLogo.naturalHeight*scale;for(const wall of [studioWall,studioPackWall,studioWarehouseWall,studioMaltWall])wall.getContext('2d').drawImage(studioLogo,64-w/2,64-h/2,w,h);};
 studioLogo.src='assets/art/brand/logo.png';
 function wallTexture(tile,x,y){
  const {levelIndex,level}=V;
  if(tile===4)return SceneArt.rack;
  if(tile===5)return SceneArt.siloWall;
  if((levelIndex===2||levelIndex===3)&&tile===3)return SceneArt.maltDoor;
  if(tile===2)return SceneArt.wall((x+y)%3);
  if(tile===1){
   const branded=level.logoWalls.some(([lx,ly])=>x===lx&&y===ly);
   if(levelIndex===1)return branded?studioPackWall:SceneArt.packWall;
   if(levelIndex===2)return branded?studioWarehouseWall:SceneArt.warehouseWall;
   if(levelIndex===3)return branded?studioMaltWall:SceneArt.maltWall;
   if(branded)return studioWall;
  }
  return textures[tile];
 }
 function sprite(type){let c=document.createElement('canvas');c.width=c.height=128;let g=c.getContext('2d');g.lineWidth=4;g.strokeStyle='#25362d';const ellipse=(x,y,rx,ry,col)=>{g.fillStyle=col;g.beginPath();g.ellipse(x,y,rx,ry,0,0,7);g.fill();g.stroke();};if(type.startsWith('enemy')){let t=Number(type.slice(-1)),col=['#9cac44','#c5a453','#9d8bb5'][t];g.fillStyle='#0005';g.beginPath();g.ellipse(64,116,40,8,0,0,7);g.fill();for(let i=0;i<12;i++){let a=i*Math.PI/6,x=64+Math.cos(a)*43,y=61+Math.sin(a)*40;g.strokeStyle='#25362d';g.lineWidth=7;g.beginPath();g.moveTo(64+Math.cos(a)*30,61+Math.sin(a)*30);g.lineTo(x,y);g.stroke();ellipse(x,y,5,5,col);}ellipse(64,64,36,t===1?43:33,col);ellipse(40,106,13,9,col);ellipse(87,106,13,9,col);g.strokeStyle='#25362d';ellipse(49,52,13,15,'#f3df9c');ellipse(80,52,13,15,'#f3df9c');ellipse(53,55,4,7,'#202820');ellipse(76,55,4,7,'#202820');g.fillStyle='#26382a';g.beginPath();g.moveTo(42,76);g.quadraticCurveTo(64,95,88,75);g.lineTo(82,96);g.lineTo(51,98);g.closePath();g.fill();g.fillStyle='#f0deb2';for(let x=49;x<85;x+=10){g.beginPath();g.moveTo(x,80);g.lineTo(x+7,81);g.lineTo(x+3,90);g.fill();}g.fillStyle='#ffffff33';g.fillRect(37,66,6,4);g.fillRect(82,69,8,5);g.fillStyle='#31473066';g.fillRect(58,30,6,5);g.fillRect(33,81,5,8);g.fillRect(90,65,5,9);if(t===1){g.fillStyle='#e9d799';g.fillRect(46,17,38,9);g.fillRect(53,8,24,12);}if(t===2){g.strokeStyle='#b9a3c8';g.lineWidth=6;for(let x of [20,107]){g.beginPath();g.moveTo(x,50);g.lineTo(x-10,23);g.lineTo(x+3,30);g.stroke();}}}else if(type==='health'){g.fillStyle='#0005';g.fillRect(20,104,90,10);g.fillStyle='#d9dab5';g.fillRect(28,40,72,67);g.strokeRect(28,40,72,67);g.fillStyle='#526e42';g.fillRect(54,48,20,48);g.fillRect(40,62,48,19);g.strokeRect(50,29,28,12);}else if(type==='ammo'){g.fillStyle='#976d3d';g.fillRect(15,54,100,57);g.strokeRect(15,54,100,57);for(let x=26;x<110;x+=22){g.fillStyle='#345336';g.fillRect(x,26,13,41);g.fillStyle='#d2b669';g.fillRect(x+3,16,7,14);}g.fillStyle='#ddc98e';g.fillRect(31,72,68,25);g.fillStyle='#3d462b';g.font='bold 12px monospace';g.font='bold 9px monospace';g.fillText('ХМЕЛЬНОЙ',37,83);g.fillText('ДОЗОР',46,93);}else if(type==='bottle'){g.fillStyle='#ddc88b';g.fillRect(54,7,20,9);g.fillStyle='#426d39';g.fillRect(55,16,18,30);g.fillRect(43,45,42,69);g.strokeRect(43,45,42,69);g.fillStyle='#e8d39a';g.fillRect(43,68,42,29);g.fillStyle='#344b2c';g.font='bold 17px monospace';g.fillText('№7',51,88);g.fillStyle='#acc773';g.fillRect(48,49,5,17);}else if(type==='can'){g.fillStyle='#c5b69b';g.fillRect(39,30,50,78);g.strokeRect(39,30,50,78);g.fillStyle='#44342c';g.fillRect(40,44,48,52);g.fillStyle='#efc86d';g.font='bold 12px monospace';g.fillText('КОТЁЛ',44,68);g.fillText('13',57,86);g.fillStyle='#f1dcac';g.fillRect(42,32,44,5);}else{ellipse(64,64,18,18,type==='foam'?'#f4e4b8':'#bba479');}return c;}
 const sprites=Object.fromEntries(['enemy0','enemy1','enemy2','health','ammo','bottle','can','cork','foam'].map(s=>[s,sprite(s)]));
 const stellaSprite=document.createElement('canvas');stellaSprite.width=stellaSprite.height=128;const stellaImage=document.createElement('img');
 stellaImage.onload=()=>{const g=stellaSprite.getContext('2d');g.clearRect(0,0,128,128);g.imageSmoothingEnabled=true;const scale=Math.min(112/stellaImage.naturalWidth,124/stellaImage.naturalHeight),w=stellaImage.naturalWidth*scale,h=stellaImage.naturalHeight*scale;g.drawImage(stellaImage,64-w/2,126-h,w,h);};
 stellaImage.src='assets/art/stella-rescued-full.webp';
 function background(){const {player,levelIndex,level}=V;ctx.fillStyle='#263629';ctx.fillRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,VIEW/2);sky.addColorStop(0,level.ceiling);sky.addColorStop(1,levelIndex===3?'#9b8a6b':levelIndex===2?'#61685f':levelIndex?'#72909b':'#68745e');ctx.fillStyle=sky;ctx.fillRect(0,0,W,VIEW/2);let floor=ctx.createLinearGradient(0,VIEW/2,0,VIEW);floor.addColorStop(0,level.floor);floor.addColorStop(1,levelIndex===3?'#403729':'#302f24');ctx.fillStyle=floor;ctx.fillRect(0,VIEW/2,W,H);for(let y=VIEW/2+5;y<VIEW;y+=3){let d=VIEW/(2*(y-VIEW/2));let alpha=Math.min(.17,.8/d);ctx.fillStyle=`rgba(195,171,109,${alpha})`;if(Math.floor(d+player.y)%2===0)ctx.fillRect(0,y,W,1);} }
 function floorDetails(){
  const {player,levelIndex}=V,ca=Math.cos(player.a),sa=Math.sin(player.a),plane=Math.tan(FOV/2);
  for(let y=VIEW/2+8;y<VIEW;y+=4){const dist=VIEW/(2*(y-VIEW/2)),alpha=Math.min(.28,1.1/dist);
  for(let x=0;x<W;x+=12){const camera=(2*x/W-1)*plane,wx=player.x+dist*(ca-sa*camera),wy=player.y+dist*(sa+ca*camera);
  const fx=wx-Math.floor(wx),fy=wy-Math.floor(wy);if(levelIndex===2&&(fx<.06||fx>.94)&&[2,8,14,20].includes(Math.floor(wx))&&Math.floor(wy*2)%3!==0){ctx.fillStyle=`rgba(239,190,71,${alpha*2})`;ctx.fillRect(x,y,12,4);}
  else if(levelIndex===3&&((fy<.045&&Math.floor(wy)%2===0)||((Math.floor(wx*3)+Math.floor(wy*5))%17===0&&fx<.12))){ctx.fillStyle=`rgba(226,197,126,${alpha*1.7})`;ctx.fillRect(x,y,12,3);}
  else if(fx<.035||fy<.035){ctx.fillStyle=levelIndex?`rgba(15,39,50,${alpha})`:`rgba(20,32,24,${alpha})`;ctx.fillRect(x,y,12,4);}
  else if((Math.floor(wx)+Math.floor(wy))%2===0){ctx.fillStyle=`rgba(194,211,193,${alpha*.12})`;ctx.fillRect(x,y,12,4);}
  }}
 }
 function drawWorld(view){V=view;const {player,map}=V;background();floorDetails();for(let x=0;x<W;x+=2){let camera=(2*x/W-1)*Math.tan(FOV/2),rx=Math.cos(player.a)-Math.sin(player.a)*camera,ry=Math.sin(player.a)+Math.cos(player.a)*camera;let mx=Math.floor(player.x),my=Math.floor(player.y),ddx=Math.abs(1/rx),ddy=Math.abs(1/ry),sx=rx<0?-1:1,sy=ry<0?-1:1,distx=(rx<0?player.x-mx:mx+1-player.x)*ddx,disty=(ry<0?player.y-my:my+1-player.y)*ddy,side=0,tile=0;for(let j=0;j<64;j++){if(distx<disty){distx+=ddx;mx+=sx;side=0;}else{disty+=ddy;my+=sy;side=1;}tile=map[my]?.[mx]??1;if(tile)break;}let d=Math.max(.05,side?disty-ddy:distx-ddx);depth[x]=depth[x+1]=d;let wall=side?player.x+d*rx:player.y+d*ry;wall-=Math.floor(wall);let column=Math.min(127,Math.floor(wall*128));if((side===0&&rx<0)||(side===1&&ry>0))column=127-column;let h=VIEW/d,y=(VIEW-h)/2;ctx.drawImage(wallTexture(tile,mx,my),column,0,1,128,x,y,2,h);ctx.fillStyle=`rgba(9,20,14,${Math.min(.83,d*.058+(side?.16:0))})`;ctx.fillRect(x,y,2,h);}}
 function project(x,y){const {player}=V;let dx=x-player.x,dy=y-player.y,d=dx*Math.cos(player.a)+dy*Math.sin(player.a);return{d,x:W/2+(-dx*Math.sin(player.a)+dy*Math.cos(player.a))*W/(2*Math.tan(FOV/2)*d)};}
 function bill(img,x,y,size=1,z=0,hit=0,aspect=1){let p=project(x,y);if(p.d<.15)return null;let h=VIEW/p.d*size,w=h*aspect,left=p.x-w/2,top=VIEW/2+VIEW/p.d*.5-h-z*VIEW/p.d;if(left>W||left+w<0)return null;ctx.globalAlpha=1;for(let sx=Math.max(0,Math.floor(left));sx<Math.min(W,left+w);sx+=2){if(p.d>=depth[sx])continue;ctx.drawImage(img,Math.max(0,Math.floor((sx-left)/w*128)),0,1,128,sx,top,2,h);}if(hit>0&&p.x>=0&&p.x<W&&p.d<depth[Math.floor(p.x)]){ctx.fillStyle='#f8df9a';ctx.fillRect(p.x-16,top-9,32*hit/.16,3);}return{x:p.x,top,w,h,d:p.d,visible:p.x>=0&&p.x<W&&p.d<depth[Math.floor(p.x)]};}
 function drawSprites(view){V=view;const {player,props,enemies,items,shots,particles,clock,levelIndex,level,stellaVisible}=V;const forkliftType=e=>e.type===6||e.type===7;let all=[...props.map(p=>({...p,aspect:['bottles','cans'].includes(p.type)?1.7:1,img:SceneArt.prop(p.type,['aspiration','screw','hatch'].includes(p.type)?Number(p.active):Math.floor(clock*5)%2)})),...enemies.filter(e=>e.hp>0).map(e=>({...e,enemy:e,img:(forkliftType(e)?SceneArt.forklift(e.type,e.mode,Math.floor(clock*10)%2):e.type>2?SceneArt.monster(e.type,e.attack>.5?1:Math.floor(clock*6+e.seed)%2):sprites['enemy'+e.type]),size:forkliftType(e)?1.25:e.type===10?1.25:e.type===5?1.15:e.type===8?.7:.85,aspect:forkliftType(e)?1.25:1,z:forkliftType(e)?0:e.type===9?.13+Math.sin(clock*4+e.seed)*.04:Math.sin(clock*5+e.seed)*.025})),...(stellaVisible&&levelIndex===3?[{x:level.stella[0],y:level.stella[1],img:stellaSprite,size:1.12,z:Math.sin(clock*2)*.008}]:[]),...items.map(i=>({...i,img:sprites[i.type],size:.52})),...shots.map(s=>({...s,img:sprites[s.type],size:s.type==='foam'?.2:.24,z:.35+Math.sin(Math.min(1,s.age)*Math.PI)*.2})),...(view.extra||[])];all.sort((a,b)=>Math.hypot(b.x-player.x,b.y-player.y)-Math.hypot(a.x-player.x,a.y-player.y));const rects=[];for(let e of all){const r=bill(e.img,e.x,e.y,e.size,e.z||0,e.hit||0,e.aspect||1);if(r&&e.enemy)rects.push({...r,enemy:e.enemy});}for(let q of particles){let p=project(q.x,q.y);if(p.d<.1||p.x<0||p.x>=W||p.d>depth[Math.floor(p.x)])continue;let y=VIEW/2+(.4-q.z)*VIEW/p.d,r=Math.min(20,5/p.d);ctx.fillStyle=q.color;ctx.fillRect(p.x,y,r,r);}return rects;}
 // Called on level load; later tracks build per-level caches (lightmaps, floor textures) here.
 function setLevel(index,level,map){current.index=index;current.level=level;current.map=map;}
 // Called when map cells change at runtime (e.g. a secret wall opens).
 function onMapChange(){}
 // Called after an async image (logo, Stella) finished painting into a texture canvas.
 function invalidate(source){}
 // Draws the 3D view and returns screen rects of visible enemies for HUD overlays.
 function render(view){ctx.imageSmoothingEnabled=false;drawWorld(view);return drawSprites(view);}
 return {render,setLevel,onMapChange,invalidate,drawWorld,drawSprites,project,stats,depth,sprites,textures,wallTexture};
})();
